spring.datasource.url=jdbc:postgresql://localhost:5432/market_db
spring.datasource.username=postgres
spring.datasource.password=ogwaa123

app.jwt.secret=mySecretKeyForJWTTokenGenerationAndValidationPurposeOnly123456789012
app.jwt.expiration=86400000

paystack.api.key=pk_test_6a1a73b27bfabc495f2566160f295a1e66c93fd0
paystack.api.secret=sk_test_d00a8a661d4dec8e0eeae18fac6ccfa331bce99c
paystack.api.url=https://api.paystack.co
paystack.callback.url=https://your-ngrok-url/api/v1/webhooks/paystack

