server:
  port: ${PORT:5000}

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: false

logging:
  level:
    root: warn
    com:
      market: warn
    org:
      flywaydb: warn