spring.application.name=market

spring.datasource.url=jdbc:postgresql://localhost:5432/market_db
spring.datasource.username=postgres
spring.datasource.password=ogwaa123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Server Port
server.port=8085

# Paystack Configuration
paystack.api.key=${PAYSTACK_API_KEY:pk_test_6a1a73b27bfabc495f2566160f295a1e66c93fd0}
paystack.api.secret=${PAYSTACK_SECRET_KEY:sk_test_d00a8a661d4dec8e0eeae18fac6ccfa331bce99c}
paystack.api.url=https://api.paystack.co

# Use Ngrok public URL for callback
paystack.callback.url=${APP_CALLBACK_URL:https://dawnlike-solomon-lightfootedly.ngrok-free.dev/api/v1/webhooks/paystack}

# JWT Configuration
app.jwt.secret=${JWT_SECRET:mySecretKeyForJWTTokenGenerationAndValidationPurposeOnly123456789}
app.jwt.expiration=86400000
